vim.pack.add({
    "https://www.github.com/nvim-lua/plenary.nvim",
    "https://www.github.com/nvim-telescope/telescope-fzf-native.nvim",
    "https://www.github.com/nvim-telescope/telescope-ui-select.nvim",
    "https://www.github.com/nvim-tree/nvim-web-devicons",
})
-- require("telescope-fzf-native.nvim").setup({
-- 			build = "make",
-- })
-- vim.pack.add({
--     {src="https://www.github.com/nvim-telescope/telescope-ui-select.nvim" },
--     {src=	"https://www.github.com/nvim-tree/nvim-web-devicons", name="nvim-web-devicons"}
-- })
require("nvim-web-devicons").setup({
    enabled = vim.g.have_nerd_font,
})
--
vim.pack.add({ "https://www.github.com/nvim-telescope/telescope.nvim" })
require("telescope").setup({
    event = "VimEnter",
    picker = {
        buffers = {
            ignore_current_buffer = true,
            sort_lastused = true,
        },
    },
    defaults = {
        file_ignore_patterns = {
            "node_modules/.*",
            "zig-pkg/.*",
            "%.git/.*",
        },
        layout_strategy = "vertical",
        layout_config = {
            height = 0.95,
            width = 0.95,
            mirror = true,
            preview_cutoff = 0,
            vertical = {
                preview_height = 0.4,
            },
        },
    },
})

vim.keymap.set("n", "<leader>sh", function()
    require("telescope.builtin").help_tags()
end, { desc = "[S]earch [H]elp" })
vim.keymap.set("n", "<leader>sk", function()
    require("telescope.builtin").keymaps()
end, { desc = "[S]earch [K]eymaps" })
vim.keymap.set("n", "<leader>sf", function()
    require("telescope.builtin").find_files()
end, { desc = "[S]earch [F]iles" })
vim.keymap.set("n", "<leader>ss", function()
    require("telescope.builtin").builtin()
end, { desc = "[S]earch [S]elect Telescope" })
vim.keymap.set("n", "<leader>sw", function()
    require("telescope.builtin").grep_string()
end, { desc = "[S]earch current [W]ord" })
vim.keymap.set("n", "<leader>sg", function()
    require("telescope.builtin").live_grep()
end, { desc = "[S]earch by [G]rep" })
vim.keymap.set("n", "<leader>sd", function()
    require("telescope.builtin").diagnostics()
end, { desc = "[S]earch [D]iagnostics" })
vim.keymap.set("n", "<leader>sr", function()
    require("telescope.builtin").resume()
end, { desc = "[S]earch [R]esume" })
vim.keymap.set("n", "<leader>s.", function()
    require("telescope.builtin").oldfiles()
end, { desc = '[S]earch Recent Files ("." for repeat)' })
vim.keymap.set("n", "<leader><leader>", function()
    require("telescope.builtin").buffers()
end, { desc = "[ ] Find existing buffers" })
vim.keymap.set("n", "<leader>/", function()
    require("telescope.builtin").current_buffer_fuzzy_find()
    -- require("telescope.builtin").current_buffer_fuzzy_find(require("telescope.themes").get_dropdown({
    -- 	winblend = 10,
    -- 	previewer = false,
    -- }))
end, { desc = "[/] Fuzzily search in current buffer" })
vim.keymap.set("n", "<leader>s/", function()
    require("telescope.builtin").live_grep({
        grep_open_files = true,
        prompt_title = "Live Grep in Open Files",
    })
end, { desc = "[S]earch [/] in Open Files" })
vim.keymap.set("n", "<leader>sn", function()
    require("telescope.builtin").find_files({
        cwd = vim.fn.stdpath("config"),
    })
end, { desc = "[S]earch [N]eovim files" })
-- NOTE: FOLLOWING KEY MAP IS GENERATED BY AI AND NOT REVIEWED
-- TODO: MUST UNDERSTAND WHAT IS HAPPENING
vim.keymap.set("n", "<leader>gr", function()
    require("telescope.builtin").lsp_references()
end, { desc = "[G]o to [R]eferences with telescope" })
vim.keymap.set("n", "<leader>gc", function()
    local pickers = require("telescope.pickers")
    local finders = require("telescope.finders")
    local conf = require("telescope.config").values
    local actions = require("telescope.actions")
    local action_state = require("telescope.actions.state")
    local previewers = require("telescope.previewers")

    -- Get changed files (modified, staged, unstaged)
    local diff_handle = io.popen("git diff --name-only HEAD 2>/dev/null")
    local diff_result = diff_handle:read("*a")
    diff_handle:close()

    -- Get untracked files
    local untracked_handle = io.popen("git ls-files --others --exclude-standard 2>/dev/null")
    local untracked_result = untracked_handle:read("*a")
    untracked_handle:close()

    -- Combine results
    local files = {}
    local seen = {}
    for file in diff_result:gmatch("[^\n]+") do
        if not seen[file] then
            table.insert(files, file)
            seen[file] = true
        end
    end
    for file in untracked_result:gmatch("[^\n]+") do
        if not seen[file] then
            table.insert(files, file .. " [new]")
            seen[file] = true
        end
    end

    if #files == 0 then
        vim.notify("No changes found", vim.log.levels.INFO)
        return
    end

    -- Custom previewer that shows git diff
    local git_diff_previewer = previewers.new_termopen_previewer({
        get_command = function(entry)
            local file = entry.value:gsub(" %[new%]$", "")
            if entry.value:match("%[new%]$") then
                return { "cat", file }
            end
            return { "git", "diff", "HEAD", "--", file }
        end,
    })

    pickers
        .new({}, {
            prompt_title = "Git Changes",
            finder = finders.new_table({
                results = files,
                entry_maker = function(entry)
                    return {
                        value = entry,
                        display = entry,
                        ordinal = entry,
                    }
                end,
            }),
            sorter = conf.generic_sorter({}),
            previewer = git_diff_previewer,
            attach_mappings = function(_, map)
                local open_file = function(prompt_bufnr)
                    local selection = action_state.get_selected_entry()
                    actions.close(prompt_bufnr)
                    local file = selection.value:gsub(" %[new%]$", "")
                    vim.cmd("edit " .. vim.fn.fnameescape(file))
                end
                map("i", "<CR>", open_file)
                map("n", "<CR>", open_file)
                return true
            end,
        })
        :find()
end, { desc = "[G]it [C]hanges" })
vim.keymap.set("n", "<leader>sz", function()
    local pickers = require("telescope.pickers")
    local finders = require("telescope.finders")
    local conf = require("telescope.config").values
    local actions = require("telescope.actions")
    local action_state = require("telescope.actions.state")

    -- Get directories from fd and prepend "."
    local handle = io.popen("fd --type d --exclude /prisma --exclude /generated")
    local result = handle:read("*a")
    handle:close()

    local dirs = { "." } -- Start with project root
    for dir in result:gmatch("[^\n]+") do
        table.insert(dirs, dir)
    end

    pickers
        .new({}, {
            prompt_title = "Find Directories",
            finder = finders.new_table({ results = dirs }),
            sorter = conf.generic_sorter({}),
            attach_mappings = function(_, map)
                local open_in_oil = function(prompt_bufnr)
                    local selection = action_state.get_selected_entry()
                    actions.close(prompt_bufnr)
                    require("oil").open(selection[1])
                end

                map("i", "<CR>", open_in_oil)
                map("n", "<CR>", open_in_oil)

                return true
            end,
        })
        :find()
end, { desc = "[S]earch directori[Z]" })
