-- plugins/telescope.lua:
return { -- Fuzzy Finder (files, lsp, etc)
	"nvim-telescope/telescope.nvim",
	event = "VimEnter",
	branch = "0.1.x",
	dependencies = {
		"nvim-lua/plenary.nvim",
		{ -- If encountering errors, see telescope-fzf-native README for installation instructions
			"nvim-telescope/telescope-fzf-native.nvim",
			build = "make",
			cond = function()
				return vim.fn.executable("make") == 1
			end,
		},
		{ "nvim-telescope/telescope-ui-select.nvim" },
		{
			"nvim-tree/nvim-web-devicons",
			enabled = vim.g.have_nerd_font,
		},
	},
	keys = {
		{
			"<leader>sh",
			function()
				require("telescope.builtin").help_tags()
			end,
			desc = "[S]earch [H]elp",
		},
		{
			"<leader>sk",
			function()
				require("telescope.builtin").keymaps()
			end,
			desc = "[S]earch [K]eymaps",
		},
		{
			"<leader>sf",
			function()
				require("telescope.builtin").find_files()
			end,
			desc = "[S]earch [F]iles",
		},
		{
			"<leader>ss",
			function()
				require("telescope.builtin").builtin()
			end,
			desc = "[S]earch [S]elect Telescope",
		},
		{
			"<leader>sw",
			function()
				require("telescope.builtin").grep_string()
			end,
			desc = "[S]earch current [W]ord",
		},
		{
			"<leader>sg",
			function()
				require("telescope.builtin").live_grep()
			end,
			desc = "[S]earch by [G]rep",
		},
		{
			"<leader>sd",
			function()
				require("telescope.builtin").diagnostics()
			end,
			desc = "[S]earch [D]iagnostics",
		},
		{
			"<leader>sr",
			function()
				require("telescope.builtin").resume()
			end,
			desc = "[S]earch [R]esume",
		},
		{
			"<leader>s.",
			function()
				require("telescope.builtin").oldfiles()
			end,
			desc = '[S]earch Recent Files ("." for repeat)',
		},
		{
			"<leader><leader>",
			function()
				require("telescope.builtin").buffers()
			end,
			desc = "[ ] Find existing buffers",
		},
		{
			"<leader>/",
			function()
				require("telescope.builtin").current_buffer_fuzzy_find(require("telescope.themes").get_dropdown({
					winblend = 10,
					previewer = false,
				}))
			end,
			desc = "[/] Fuzzily search in current buffer",
		},
		{
			"<leader>s/",
			function()
				require("telescope.builtin").live_grep({
					grep_open_files = true,
					prompt_title = "Live Grep in Open Files",
				})
			end,
			desc = "[S]earch [/] in Open Files",
		},
		{
			"<leader>sn",
			function()
				require("telescope.builtin").find_files({
					cwd = vim.fn.stdpath("config"),
				})
			end,
			desc = "[S]earch [N]eovim files",
		},
		-- NOTE: FOLLOWING KEY MAP IS GENERATED BY AI AND NOT REVIEWED
		-- TODO: MUST UNDERSTAND WHAT IS HAPPENING
		{
			"<leader>sz",
			function()
				local pickers = require("telescope.pickers")
				local finders = require("telescope.finders")
				local conf = require("telescope.config").values
				local actions = require("telescope.actions")
				local action_state = require("telescope.actions.state")

				-- Get directories from fd and prepend "."
				local handle = io.popen("fd --type d --exclude /prisma --exclude /generated")
				local result = handle:read("*a")
				handle:close()

				local dirs = { "." } -- Start with project root
				for dir in result:gmatch("[^\n]+") do
					table.insert(dirs, dir)
				end

				pickers
					.new({}, {
						prompt_title = "Find Directories",
						finder = finders.new_table({ results = dirs }),
						sorter = conf.generic_sorter({}),
						attach_mappings = function(_, map)
							local open_in_oil = function(prompt_bufnr)
								local selection = action_state.get_selected_entry()
								actions.close(prompt_bufnr)
								require("oil").open(selection[1])
							end

							map("i", "<CR>", open_in_oil)
							map("n", "<CR>", open_in_oil)

							return true
						end,
					})
					:find()
			end,
			desc = "[S]earch directori[Z]",
		},
	},
	opts = {
		picker = {
			buffers = {
				ignore_current_buffer = true,
				sort_lastused = true,
			},
		},
		defaults = {
			file_ignore_patterns = {
				"node_modules/.*",
				"%.git/.*",
			},
		},
	},

	-- opts = function()
	--     local themes = require('telescope.themes')
	--     return {
	--         extensions = {
	--             ['ui-select'] = {themes.get_dropdown()}
	--         },
	--         picker = {
	--             buffers = {
	--                 ignore_current_buffer = true,
	--                 sort_lastused = true,
	--             },
	--         },
	--         defaults = {
	--             mappings = {
	--                 i = {
	--                     ["<C-j>"] = "move_selection_next",
	--                     ["<C-k>"] = "move_selection_previous"
	--                 },
	--                 n = {
	--                     ["j"] = "move_selection_next",
	--                     ["k"] = "move_selection_previous",
	--                 }
	--             },
	--             file_ignore_patterns = { "node%_modules/.*" },
	--
	--         }
	--     }
	-- end,

	-- config = function()
	--     -- require('telescope').setup(opts)
	--     -- Load extensions
	--     pcall(require('telescope').load_extension, 'fzf')
	--     pcall(require('telescope').load_extension, 'ui-select')
	-- end
}
